import 'package:flutter/material.dart';
import 'gym_models.dart';

/// 🏋️ Rutinas predefinidas famosas - Listo para copiar y personalizar
final List<PresetRoutine> presetRoutines = [
  // 1️⃣ Arnold Classic Split
  PresetRoutine(
    id: 'arnold_classic',
    name: 'Arnold Classic Split',
    description: 'Rutina legendaria de Arnold Schwarzenegger. 6 días/semana enfocada en volumen alto e hipertrofia. Ideal para avanzados.',
    goal: 'mass',
    level: 'advanced',
    icon: Icons.military_tech,
    days: [
      PresetDay(
        name: 'Pecho + Espalda',
        icon: '💪',
        exercises: [
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
            targetRPE: 8.0,
          ),
          PresetExercise(
            exerciseId: 'incline_bench',
            name: 'Press Banca Inclinado',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'flyes',
            name: 'Aperturas con Mancuernas',
            muscleGroup: 'chest',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'pull_ups',
            name: 'Dominadas',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'deadlift',
            name: 'Peso Muerto',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 180,
            targetRPE: 9.0,
          ),
        ],
      ),
      PresetDay(
        name: 'Hombros + Brazos',
        icon: '🦾',
        exercises: [
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'lateral_raise',
            name: 'Elevaciones Laterales',
            muscleGroup: 'shoulders',
            category: 'isolation',
            targetSets: 4,
            targetReps: 12,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'barbell_curl',
            name: 'Curl con Barra',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'tricep_dips',
            name: 'Fondos en Paralelas',
            muscleGroup: 'triceps',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'hammer_curl',
            name: 'Curl Martillo',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Piernas',
        icon: '🦵',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 5,
            targetReps: 8,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'leg_press',
            name: 'Prensa',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 4,
            targetReps: 12,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'leg_curl',
            name: 'Curl Femoral',
            muscleGroup: 'legs',
            category: 'isolation',
            targetSets: 4,
            targetReps: 12,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'calf_raise',
            name: 'Elevación de Gemelos',
            muscleGroup: 'calves',
            category: 'isolation',
            targetSets: 5,
            targetReps: 15,
            restSec: 60,
          ),
        ],
      ),
    ],
  ),

  // 2️⃣ PPL para Novatos
  PresetRoutine(
    id: 'ppl_beginner',
    name: 'PPL Novato',
    description: 'Push Pull Legs clásico. 6 días/semana con volumen moderado. Perfecto para principiantes que buscan estructura.',
    goal: 'general',
    level: 'beginner',
    icon: Icons.trending_up,
    days: [
      PresetDay(
        name: 'Push (Empuje)',
        icon: '⬆️',
        exercises: [
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'incline_bench',
            name: 'Press Inclinado',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'tricep_extension',
            name: 'Extensiones de Tríceps',
            muscleGroup: 'triceps',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Pull (Tirón)',
        icon: '⬇️',
        exercises: [
          PresetExercise(
            exerciseId: 'deadlift',
            name: 'Peso Muerto',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 180,
          ),
          PresetExercise(
            exerciseId: 'pull_ups',
            name: 'Dominadas',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'barbell_curl',
            name: 'Curl con Barra',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 3,
            targetReps: 10,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Legs (Piernas)',
        icon: '🦵',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 4,
            targetReps: 8,
            restSec: 180,
          ),
          PresetExercise(
            exerciseId: 'leg_press',
            name: 'Prensa',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 3,
            targetReps: 12,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'leg_curl',
            name: 'Curl Femoral',
            muscleGroup: 'legs',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'calf_raise',
            name: 'Elevación de Gemelos',
            muscleGroup: 'calves',
            category: 'isolation',
            targetSets: 4,
            targetReps: 15,
            restSec: 60,
          ),
        ],
      ),
    ],
  ),

  // 3️⃣ Full Body 3x/semana
  PresetRoutine(
    id: 'full_body_3x',
    name: 'Full Body 3x Semana',
    description: 'Rutina de cuerpo completo 3 días/semana. Ideal para principiantes o personas con poco tiempo.',
    goal: 'general',
    level: 'beginner',
    icon: Icons.all_inclusive,
    days: [
      PresetDay(
        name: 'Día A',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 2,
            targetReps: 10,
            restSec: 90,
          ),
        ],
      ),
      PresetDay(
        name: 'Día B',
        exercises: [
          PresetExercise(
            exerciseId: 'deadlift',
            name: 'Peso Muerto',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 180,
          ),
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'pull_ups',
            name: 'Dominadas',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'leg_press',
            name: 'Prensa',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 3,
            targetReps: 12,
            restSec: 90,
          ),
        ],
      ),
      PresetDay(
        name: 'Día C',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'barbell_curl',
            name: 'Curl con Barra',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 2,
            targetReps: 12,
            restSec: 60,
          ),
        ],
      ),
    ],
  ),

  // 4️⃣ Hipertrofia Avanzada
  PresetRoutine(
    id: 'hypertrophy_advanced',
    name: 'Hipertrofia Avanzada',
    description: 'Rutina de 5 días enfocada en máximo crecimiento muscular. Volumen alto, intensidad controlada.',
    goal: 'mass',
    level: 'advanced',
    icon: Icons.auto_awesome,
    days: [
      PresetDay(
        name: 'Pecho',
        icon: '💪',
        exercises: [
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 4,
            targetReps: 8,
            restSec: 120,
            targetRPE: 8.0,
          ),
          PresetExercise(
            exerciseId: 'incline_bench',
            name: 'Press Inclinado',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'flyes',
            name: 'Aperturas',
            muscleGroup: 'chest',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'cable_crossover',
            name: 'Cruces en Polea',
            muscleGroup: 'chest',
            category: 'isolation',
            targetSets: 3,
            targetReps: 15,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Espalda',
        icon: '🔙',
        exercises: [
          PresetExercise(
            exerciseId: 'deadlift',
            name: 'Peso Muerto',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 4,
            targetReps: 6,
            restSec: 180,
            targetRPE: 9.0,
          ),
          PresetExercise(
            exerciseId: 'pull_ups',
            name: 'Dominadas',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'lat_pulldown',
            name: 'Jalones',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 3,
            targetReps: 12,
            restSec: 90,
          ),
        ],
      ),
      PresetDay(
        name: 'Hombros',
        icon: '🦾',
        exercises: [
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 4,
            targetReps: 8,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'lateral_raise',
            name: 'Elevaciones Laterales',
            muscleGroup: 'shoulders',
            category: 'isolation',
            targetSets: 4,
            targetReps: 12,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'rear_delt_fly',
            name: 'Pájaros',
            muscleGroup: 'shoulders',
            category: 'isolation',
            targetSets: 4,
            targetReps: 15,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'face_pull',
            name: 'Face Pulls',
            muscleGroup: 'shoulders',
            category: 'isolation',
            targetSets: 3,
            targetReps: 15,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Piernas',
        icon: '🦵',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 5,
            targetReps: 8,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'leg_press',
            name: 'Prensa',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 4,
            targetReps: 12,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'leg_curl',
            name: 'Curl Femoral',
            muscleGroup: 'legs',
            category: 'isolation',
            targetSets: 4,
            targetReps: 12,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'leg_extension',
            name: 'Extensiones',
            muscleGroup: 'legs',
            category: 'isolation',
            targetSets: 4,
            targetReps: 15,
            restSec: 60,
          ),
        ],
      ),
      PresetDay(
        name: 'Brazos',
        icon: '💪',
        exercises: [
          PresetExercise(
            exerciseId: 'barbell_curl',
            name: 'Curl con Barra',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'tricep_dips',
            name: 'Fondos en Paralelas',
            muscleGroup: 'triceps',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'hammer_curl',
            name: 'Curl Martillo',
            muscleGroup: 'biceps',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'tricep_extension',
            name: 'Extensiones de Tríceps',
            muscleGroup: 'triceps',
            category: 'isolation',
            targetSets: 3,
            targetReps: 12,
            restSec: 60,
          ),
        ],
      ),
    ],
  ),

  // 5️⃣ Calistenia Full Body
  PresetRoutine(
    id: 'calisthenics_full',
    name: 'Calistenia Full Body',
    description: 'Entrenamiento con peso corporal. Sin pesas, enfocado en control, fuerza relativa y habilidad.',
    goal: 'strength',
    level: 'intermediate',
    icon: Icons.sports_gymnastics,
    days: [
      PresetDay(
        name: 'Día 1',
        exercises: [
          PresetExercise(
            exerciseId: 'pull_ups',
            name: 'Dominadas',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 5,
            targetReps: 8,
            restSec: 120,
            notes: 'Control máximo',
          ),
          PresetExercise(
            exerciseId: 'push_ups',
            name: 'Flexiones',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 4,
            targetReps: 15,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'dips',
            name: 'Fondos',
            muscleGroup: 'triceps',
            category: 'compound',
            targetSets: 4,
            targetReps: 10,
            restSec: 90,
          ),
          PresetExercise(
            exerciseId: 'pistol_squat',
            name: 'Sentadilla Pistol',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 3,
            targetReps: 8,
            restSec: 120,
          ),
        ],
      ),
      PresetDay(
        name: 'Día 2',
        exercises: [
          PresetExercise(
            exerciseId: 'muscle_ups',
            name: 'Muscle Ups',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 180,
          ),
          PresetExercise(
            exerciseId: 'handstand_pushup',
            name: 'Flexiones Pino',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 4,
            targetReps: 8,
            restSec: 120,
          ),
          PresetExercise(
            exerciseId: 'leg_raises',
            name: 'Elevaciones de Piernas',
            muscleGroup: 'abs',
            category: 'isolation',
            targetSets: 4,
            targetReps: 15,
            restSec: 60,
          ),
          PresetExercise(
            exerciseId: 'nordic_curl',
            name: 'Nordic Curl',
            muscleGroup: 'legs',
            category: 'isolation',
            targetSets: 3,
            targetReps: 8,
            restSec: 120,
          ),
        ],
      ),
    ],
  ),

  // 6️⃣ Fuerza 5x5
  PresetRoutine(
    id: 'strength_5x5',
    name: 'Fuerza 5x5',
    description: 'Programa de fuerza pura. 5 series de 5 reps en grandes levantamientos. Ganar fuerza máxima.',
    goal: 'strength',
    level: 'intermediate',
    icon: Icons.bolt,
    days: [
      PresetDay(
        name: 'Día A',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'bench_press',
            name: 'Press Banca',
            muscleGroup: 'chest',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'barbell_row',
            name: 'Remo con Barra',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 120,
          ),
        ],
      ),
      PresetDay(
        name: 'Día B',
        exercises: [
          PresetExercise(
            exerciseId: 'squat',
            name: 'Sentadilla',
            muscleGroup: 'legs',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'overhead_press',
            name: 'Press Militar',
            muscleGroup: 'shoulders',
            category: 'compound',
            targetSets: 5,
            targetReps: 5,
            restSec: 180,
            targetRPE: 8.5,
          ),
          PresetExercise(
            exerciseId: 'deadlift',
            name: 'Peso Muerto',
            muscleGroup: 'back',
            category: 'compound',
            targetSets: 1,
            targetReps: 5,
            restSec: 240,
            targetRPE: 9.0,
            notes: 'Solo 1 serie pesada',
          ),
        ],
      ),
    ],
  ),
];
